### ISSUE TITLE
Two jQuery UI effects and a custom widget

### ISSUE THREAD

**Issue by axeberg** [chas-academy/05-trello-clone-aminoaarab#1]
Hi @aminoaarab you need to add the following in order to get a passing grade on this assignment:

- [ ]  Minst **två valfria effekter** från JQuery UI
- [ ]  Minst en egenskapad enkel JQuery UI **[Widget](http://learn.jquery.com/jquery-ui/widget-factory/)**

**Comment by axeberg** [comment]
@aminoaarab  make sure to mention me when you close this issue to indicate that this has been deployed and is ready for grading.

**Comment by aminoaarab** [comment]
@axelolsson The "Light/dark theme" - button should now be a widget. You can also find jQuery effects on the "delete list (X)" - button, the "hide/show board" - button, there is also an date picker when you create a new list.

Can you specify the bug a bit more?
